apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: aipfm-backend:latest
        imagePullPolicy: IfNotPresent
        command: ["celery", "-A", "backend", "worker", "-l", "info"]
        envFrom:
        - configMapRef:
            name: aipfm-config
        - secretRef:
            name: aipfm-secrets
